djangogram/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    # path("users/", include("djangogram.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here

    # /
    path("", include("djangogram.users.urls", namespace="users")),
    # /posts
    path("posts/", include("djangogram.posts.urls", namespace="posts"))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

djangogram/djangogram/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [

    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('<int:post_id>/post_update', views.post_update, name="post_update"),
    path('<int:comment_id>/comment_create', views.comment_create, name="comment_create"),
    path('<int:comment_id>/comment_delete', views.comment_delete, name="comment_delete"),
     # /posts/5/post_like/
    path('<int:post_id>/post_like', views.post_like, name="post_like"),
]

djangogram/djangogram/users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path('', views.main, name='main'),
    path('signup/', views.signup, name='signup'),
]

djangogram/djangogram/posts/models.py
from django.db import models
from djangogram.users import models as user_model

class TimeStampedModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    create_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        abstract = True

# Create your models here.
class Post(TimeStampedModel):
    author = models.ForeignKey(
                user_model.User, 
                null=True, 
                on_delete=models.CASCADE, 
                related_name='post_author'
                )
    image = models.ImageField(blank=False)
    caption = models.TextField(blank=False)
    image_likes = models.ManyToManyField(
        user_model.User, 
        blank=True,
        related_name='post_image_likes')

    def __str__(self):
        return f"{self.author}:{self.caption}"


class Comment(TimeStampedModel):
    author = models.ForeignKey(
                user_model.User, 
                null=True, 
                on_delete=models.CASCADE, 
                related_name='comment_author'
                )
    posts = models.ForeignKey(
                Post, 
                null=True, 
                on_delete=models.CASCADE, 
                related_name='comment_post'
                ) 
    contents = models.TextField(blank=True)

djangogram/djangogram/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('C', 'Custum'),
    ]

    #: First and last name do not cover name patterns around the globe
    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    user_name = models.CharField(blank=True, max_length=255)
    profile_photo = models.ImageField(blank=True)
    website = models.URLField(blank=True)
    bio = models.TextField(blank=True)
    email = models.CharField(blank=True, max_length=255)
    phone_number = models.CharField(blank=True, max_length=255)
    gender = models.CharField(blank=True, choices=GENDER_CHOICES, max_length=255)

    followers = models.ManyToManyField("self")
    following = models. ManyToManyField("self")

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

djangogram/djangogram/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model, forms
from django.utils.translation import gettext_lazy as _
from django import forms as django_forms

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

class SignUpForm(django_forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'name', 'username', 'password']

        # labels = {
        #     'email':'이메일주소',
        #     'name':'성명',
        #     'username':'사용자 이름',
        #     'password':'비밀번호',
        # }

        widgets = {
            'email':django_forms.TextInput(attrs={'placeholder':'이메일주소'}),
            'name':django_forms.TextInput(attrs={'placeholder':'성명'}),
            'username':django_forms.TextInput(attrs={'placeholder':'사용자 이름'}),
            'password':django_forms.PasswordInput(attrs={'placeholder':'비밀번호'}),
        }
    
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

djangogram/djangogram/posts/views.py
from djangogram.users.models import User as user_model
from django.shortcuts import render, get_object_or_404, redirect
from . import models, serializers
from .form import CreatePostForm, CommentForm, UpdatePostForm
from django.db.models import Q
from django.urls import reverse
from django.http import JsonResponse

# Create your views here.
def index(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            comment_form = CommentForm()
            
            user = get_object_or_404(user_model, pk=request.user.id)
            following = user.following.all()
            posts = models.Post.objects.filter(
                Q(author__in=following) | Q(author=user)
            )

            serializer = serializers.PostSerializer(posts, many=True)
            print(serializer.data)
            return render(
                request, 
                'posts/main.html', 
                {"posts":serializer.data, "comment_form":comment_form}
                )

def post_create(request):
    if request.method=='GET':
        form = CreatePostForm()
        return render(request, 'posts/post_create.html', {"form":form})
        
    elif request.method == 'POST':
        if request.user.is_authenticated:
            user = get_object_or_404(user_model, pk=request.user.id)

            # image = request.FILES['image']
            # caption = request.POST['caption']

            # new_post = models.Post.objects.create(
            #     author = user,
            #     image = image, 
            #     caption = caption
            # )
            # new_post.save()

            form = CreatePostForm(request.POST, request.FILES)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = user
                post.save()
            else:
                print(form.errors)

            return render(request, 'posts/main.html')
        
        else:
            return render(request, 'users/main.html')

def comment_create(request, comment_id):
    if request.user.is_authenticated:
        post = get_object_or_404(models.Post, pk=comment_id)

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.posts = post
            comment.save()

            return redirect(reverse('posts:index') + "#comment-"+ str(comment.id))

        else:
            return render(request, 'users/main.html')


def post_update(request, post_id):
    if request.user.is_authenticated:
        # 작성자 체크
        post = get_object_or_404(models.Post, pk=post_id)
        if request.user != post.author:
            return redirect(revers('posts:index'))
        # GET 요청
        if request.method == 'GET':
            form = UpdatePostForm(instance=post)
            return render(
                request,
                'posts/post_update.html',
                {"form" : form, "post" : post}
            )
    
        elif request.method =='POST':
            # 업데이트 버튼 클릭 후 저장을 위한 post api 요청 로직
            form = UpdatePostForm(request.POST)
            if form.is_valid():
                post.caption = form.cleaned_data['caption']
                post.save()
                
            return redirect(reverse('posts:index'))
    else:
        return render(request, 'users/main.html')

def comment_delete(request, comment_id):
    if request.user.is_authenticated:
        comment = get_object_or_404(models.Comment, pk=comment_id)
        if request.user == comment.author:
            comment.delete()
        
        return redirect(reverse('posts:index'))
    
    else:
        return render(request, 'users/main.html')


def post_like(request, post_id):
    response_body = {"result": ""}

    if request.user.is_authenticated:
        if request.method == "POST":
            post = get_object_or_404(models.Post, pk=post_id)
            existed_user = post.image_likes.filter(pk=request.user.id).exists()

            if existed_user:
                # 좋아요 누른 상태일 때는 "좋아요 취소"
                post.image_likes.remove(request.user)
                response_body["result"] = "dislike"

            else:
                # 좋아요가 아닐때 "좋아요"
                post.image_likes.add(request.user)
                response_body["result"] = "like"

            post.save()
            return JsonResponse(status=200, data=response_body)

    else:
        return JsonResponse(status=403, data=response_body)

djangogram/djangogram/users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import SignUpForm

def main(request):
    if request.method == 'GET':
        return render(request, 'users/main.html')

    elif request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
             # Redirect to a success page.
            return HttpResponseRedirect(reverse('posts:index'))
        else:
            return render(request, 'users/main.html')

def signup(request):
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'users/signup.html', {'form':form})

    elif request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                # Redirect to a success page.
                return HttpResponseRedirect(reverse('posts:index'))
    
        return render(request, 'users/main.html')

djangogram/djangogram/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UFT-8">
    <meta name="viewport" content="width-device-width, initial-scale=1.0">
    <meta http-equiv="%-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/users/main.css' %}">
    <title>{% block title %}{% endblock %}Djangogram</title>
</head>
<body>
    <div>
        {% block content %} {% endblock %}
    </div>

    {% include "users/footer.html" %}

</body>
</html>

djangogram/djangogram/templates/users/footer.html
<footer>
    <div class="list">
        <ul>
            <li><a href = "#">소개</a></li>
            <li><a href = "#">도움말</a></li>
            <li><a href = "#">홍보센터</a></li>
            <li><a href = "#">API</a></li>
            <li><a href = "#">채용정보</a></li>
        </ul>
    </div>

djangogram/djangogram/templates/users/main.html
{% extends "users/base.html" %}

Here is main.html

{% block title %}
Log in
{% endblock title %}

{% block content %}

<div class="auth">
    <form action="{% url 'users:main' %}" method="post">
    {% csrf_token %}
    <input type="input" name="username" placeholder="사용자 이름">
    <input type="password" name="password" placeholder="비밀번호">
    <input type="submit" value="Login">
    </form>
</div>

<div class="auth_link">
    <a href="{% url 'users:signup' %}">Sign Up</a>
</div>

{% endblock content %}

djangogram/djangogram/templates/users/signup.html
{% extends "users/base.html" %}

{% block title %}
Log in
{% endblock title %}

<!-- <h1>Here is SignUp page</h1> -->

{% block content %}
<div class="auth">
    <form action="{% url 'users:signup'%}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{field}}
        </div>
        {% endfor %}
        <input type="submit" value="sign up">
    </form>
</div>

<!-- <a href="{%url 'users:main' %}">Login</a> -->
<div class="auth_link">
    <a href="{%url 'users:main' %}">Login</a>
</div>
{% endblock content %}

djangogram/djangogram/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}

</div>
{% endblock content %}

djangogram/djangogram/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}